post http://127.0.0.1:8000/api/login HTTP/1.1
Accept: application/json

{
    "email": "correo@gmail.com",
    "password": "12345678"
}

###
GET https://apis.datos.gob.ar/georef/api/provincias HTTP/1.1
Accept: application/json

###

post http://localhost:8000/api/logout HTTP/1.1
Accept: application/json

###
GET http://localhost:8000/api/viandas/1 HTTP/1.1
Accept: application/json


